version: '3.2'
services:
  postgres:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_DB=tasker
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'

  app:
    container_name: tg_bot
    build:
      context: app
    links:
      - postgres:postgres
    stop_signal: SIGKILL
    environment:
      DEBUG: False
      POSTGRES_DB: tasker
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      DATABASE_PORT: 5432
    depends_on:
      - postgres